---
- name: Deploy Docker Container to EC2
  hosts: my-app-stack-ec2
  become: yes
  gather_facts: no
  vars:
    image_to_deploy: "default-image:latest"
    aws_region: "ap-south-1"
  tasks:
    - name: Debug deployed image var
      debug:
        var: image_to_deploy

    - name: Install and configure everything using raw commands
      raw: |
        # Update system and install packages
        yum update -y
        yum install -y python3 python3-pip docker
        
        # Install Docker Python SDK
        pip3 install docker
        
        # Start and enable Docker
        systemctl start docker
        systemctl enable docker
        
        # Add ec2-user to docker group
        usermod -aG docker ec2-user
        
        # Wait a moment for Docker to be ready
        sleep 5
        
        # Login to ECR
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 529624055993.dkr.ecr.ap-south-1.amazonaws.com
        
        # Pull the application image
        docker pull "{{ image_to_deploy }}"
        
        # Stop existing container if it exists (ignore errors)
        docker stop my-app-container 2>/dev/null || true
        docker rm my-app-container 2>/dev/null || true
        
        # Run the new container
        docker run -d \
          --name my-app-container \
          --restart always \
          -p 80:5000 \
          "{{ image_to_deploy }}"
        
        # Verify container is running
        docker ps | grep my-app-container
      register: deploy_result
      
    - name: Show deployment result
      debug:
        var: deploy_result.stdout_lines
